#!/bin/bash

# Nginx starts as root and drops priveleges to hab, so these files need to be
# readable by hab at runtime and not just on startup. During a reconfigure
# permissions are reset, so we need to change them back in the reconfigure
# hook.
#
# See https://github.com/habitat-sh/habitat/issues/1547
chown -R hab:hab "{{pkg.svc_config_path}}" "{{pkg.svc_data_path}}" \
  "{{pkg.svc_var_path}}"
