site :opscode

metadata

cookbook 'enterprise', :git => 'https://github.com/chef-cookbooks/enterprise-chef-common', :tag => '0.10.0'
cookbook 'chef-ha-drbd', :path => '../chef-ha-drbd'
cookbook 'apt', '~> 2.0'
cookbook 'yum', '~> 3.0'

cookbook 'runit', '= 1.6.0'
