source 'https://rubygems.org'

# chef-cli pulls chef >= 15.0 which is 16.1.16 at the time of failure.
# https://github.com/chef/chef/commit/003fbc132935961e93667f11c3f45ce4914b83ac
gem 'chef', '=15.14.0'
# Used for rspec testing only
gem 'chefspec'
# chef-cli >=3.0.4 requires Ruby version >= 2.7 which chef-server isn't ready for
gem 'chef-cli', '=3.0.1'
gem 'veil', git: 'https://github.com/chef/chef_secrets.git'
