source 'https://rubygems.org'

# Used for rspec testing only
gem 'chefspec'
# chef-cli >=3.0.4 requires Ruby version >= 2.7 which chef-server isn't ready for
gem 'chef-cli', '=3.0.1'
gem 'veil', git: 'https://github.com/chef/chef_secrets.git'
