# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.define 'shortbus' do |c|
    c.vm.box     = "opscode-centos-5.5"
    c.vm.box_url = "http://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-5.5.box"
    c.vm.network :hostonly, "192.168.93.93"

    c.vm.provision :shell do |shell|
      shell.path = "postinstall.sh"
    end
  end

  # Enable SSH agent forwarding for git clones
  config.ssh.forward_agent = true
  
  # Give enough horsepower to build PC without taking all day
  # or several hours worth of swapping  Disable support we don't need
  config.vm.customize [ 
    "modifyvm", :id,
    "--memory", "1024", 
    "--cpus", "1", 
    "--usb", "off", 
    "--usbehci", "off",
    "--audio", "none"
  ]
end
