#!/usr/bin/env escript

%% -*- mode: erlang;erlang-indent-level: 4;indent-tabs-mode: nil -*-
%% ex: ft=erlang ts=4 sw=4 et

main(Args) ->
    code:add_path("deps/neotoma/ebin"),
    [PegFile, Mod, TransformMod] = Args,
    Output = filename:absname(filename:join([filename:dirname(PegFile),  "..", "src"])),
    io:format("generating parser ~s (~s) for ~s ~n", [Mod, TransformMod, PegFile]),
    Txfm = list_to_atom(TransformMod),
    ModAtom = list_to_atom(Mod),
    neotoma:file(PegFile, [{output, Output}, {transform_module, Txfm}, {module, ModAtom}]),
    io:format("wrote parser to ~s~n", [Output]).

