source "https://rubygems.org"

gemspec
# Fix gem conflict with http-accept 1.7.0 by adding explicit dependency for version 2.1.1
gem "http-accept", "2.1.1"
# For debugging in dvm
gem "pry"
gem "pry-byebug"
gem "pry-stack_explorer"
gem "rake"

# We require chef internally to get the version in
# lib/pedant/request.rb. It's really strange code and it should be
# revisited.
gem "chef", "18.8.9"

# For "rake chef_zero_spec"
# gem 'chef-zero', github: 'chef/chef-zero'

# If you want to load debugging tools into the bundle exec sandbox,
# # add these additional dependencies into Gemfile.local
eval(File.read(__FILE__ + ".local"), binding) if File.exist?(__FILE__ + ".local")

instance_eval(ENV["GEMFILE_MOD"]) if ENV["GEMFILE_MOD"]
