#!/bin/bash

# Only non-open source modules (which have names prefixed with oc_)
# are allowed to call the chef_authz module (may be renamed to
# oc_chef_authz).
if `grep -q chef_authz src/chef*`; then
    echo "ERROR: calls to chef_authz found"
    grep chef_authz src/chef*
    exit 1
fi

# The open source modules chef* must not call the private modules oc_*.
if `grep -q oc_chef src/chef*`; then
    echo "ERROR: calls to oc_chef found"
    grep oc_chef src/chef*
    exit 1
fi
