override :rabbitmq, version: "3.6.6"
override :erlang, version: "18.3"
override :lua, version: "5.1.5"
override :'omnibus-ctl', version: "master"
override :chef, version: "v12.17.44"
override :ohai, version: "8.22.1"
override :ruby, version: "2.2.6"
override :rubygems, version: "2.6.8"
