driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['..', '/home/vagrant/chef-server']

provisioner:
  name: chef_zero
  require_chef_omnibus: 14.1.12

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-11.04
    run_list: apt::default
  - name: ubuntu-10.04
    run_list: apt::default
  - name: centos-5.11
    run_list:  yum-centos::vault
  - name: centos-6.7
  - name: centos-7.2
    run_list:  yum-centos::default

suites:
  - name: default
    attributes:
      omnibus:
        build_user: vagrant
        build_user_group: vagrant
        build_user_password: vagrant
        install_dir: /opt/opscode
    run_list:
      - omnibus::default
      - zip
