source 'https://supermarket.chef.io'

cookbook 'omnibus', '~> 6.0'
cookbook 'yum-centos'
cookbook 'zip'

# Uncomment to use the latest version of the Omnibus cookbook from GitHub
# cookbook 'omnibus', github: 'chef-cookbooks/omnibus'
