source 'https://supermarket.chef.io'

# The apt cookbook is required to bring the apt cache up-to-date on Ubuntu
# systems, since the cache can become stale on older boxes.
cookbook 'apt'

cookbook 'omnibus'
cookbook 'yum-epel'
cookbook 'yum-centos'
cookbook 'zip'

# Uncomment to use the latest version of the Omnibus cookbook from GitHub
# cookbook 'omnibus', github: 'chef-cookbooks/omnibus'
