source 'https://rubygems.org'

gem 'rake'
gem 'chefspec'
gem 'berkshelf'

# Install omnibus software
group :omnibus do
  gem 'omnibus', github: 'chef/omnibus'
  gem 'omnibus-software', github: 'chef/omnibus-software'
end

group :test do
  gem 'rspec'
end
