source "https://rubygems.org"

gem "omnibus", github: "chef/omnibus", branch: "master"
gem "omnibus-software", github: "chef/omnibus-software", branch: "master"
gem "license_scout", github: "chef/license_scout", branch: "master"

# Needed to find license for private-chef-cookbooks
gem "berkshelf"

# Needed to run Travis tests
group :test do
  gem "rspec"
  gem "rake"
  gem "chefspec"
end

group :development do
  gem "test-kitchen"
  gem "kitchen-vagrant"
  gem "winrm-fs"
  gem "pry"
  gem "pry-byebug"
  gem "pry-stack_explorer"
  gem "rb-readline"
end
