source 'https://rubygems.org'

# Fix gem conflict with http-accept 1.7.0 by adding explicit dependency for version 2.1.1
gem 'http-accept', '2.1.1'
gem 'berkshelf', '~> 8.0.22'
gem 'archive-tar-minitar' # required by berkshelf for packaging operations
