source 'https://rubygems.org'

gem 'cookstyle'
gem 'chefspec'
gem 'veil', git: 'https://github.com/chef/chef_secrets', branch: 'lbaker/upgrade-erlang-24.2', ref: '5040d0daea5f643074cb6d41254cf04bfd5ba29a'
