source 'https://rubygems.org'

# Fix gem conflict with http-accept 1.7.0 by adding explicit dependency for version 2.1.1
gem 'http-accept', '2.1.1'
gem 'cookstyle'
gem 'chefspec'
gem 'veil'
gem 'chef', '~> 18.8.9' # Updated for chef 18.8.9 upgrade
