chef_api :config

metadata

def path_to_platform_cookbooks
  ENV['OPSCODE_PLATFORM_REPO'] || '~/oc/opscode-platform-cookbooks'
end

%w(opscode-dev-shim opscode-users).each do |cb|
  cookbook cb, :git => "git@github.com:opscode-cookbooks/#{cb}.git"
end

%w(users sudo opscode-lb unicorn).each do |cb|
  cookbook cb, :path => "#{path_to_platform_cookbooks}/cookbooks/#{cb}"
end
