gem 'berkshelf', '~> 2.0.14'

group :developement do
  gem 'foodcritic', '~> 3.0.3'
end

group :test do
  gem 'busser-serverspec', '~> 0.2.6'
  gem 'kitchen-vagrant', '~> 0.14.0'
  gem 'test-kitchen', '~> 1.2.1'
end