-- Revert widen_uuid_fields

BEGIN;

ALTER TABLE roles ALTER COLUMN id TYPE CHAR(32);
ALTER TABLE clients ALTER COLUMN id TYPE CHAR(32);
ALTER TABLE data_bags ALTER COLUMN id TYPE CHAR(32);
ALTER TABLE data_bag_items ALTER COLUMN id TYPE CHAR(32);
ALTER TABLE environments ALTER COLUMN id TYPE CHAR(32);

COMMIT;
