source 'https://supermarket.chef.io'

cookbook 'enterprise', git: 'https://github.com/chef-cookbooks/enterprise-chef-common', branch: 'praj/update_runit'
cookbook 'private-chef', path: './private-chef'
