#!/bin/bash

exec 2>&1

source "{{pkg.svc_config_path}}/database-migrations.sh"

# TODO
# this rsync is because the rails app needs to access the templated `config` dir
# as a subdirectory of its root install location.  Symlinking `config` from pkg.path
# doesn't work because that requires root to write in pkg.path.
# make this better somehow

cd {{pkg.svc_path}}
{{pkgPathFor "core/rsync"}}/bin/rsync -a {{pkg.path}}/oc_id/ . \
  --exclude vendor/ \
  --exclude database.yml \
  --exclude production.yml
