source 'https://rubygems.org'

gem 'dep_selector', :git => 'git://github.com/chef/dep-selector', :branch => 'master'
gem 'erlectricity', :git => 'git://github.com/marcparadise/erlectricity', :branch => 'mp/gcc-4.9.2-compat-fix'
gem 'uuidtools'
