require_relative "project/dep"
require_relative "project/project"
require_relative "project/erlang"
require_relative "project/ruby"
require_relative "project/rails"
require_relative "project/omnibus"
