#!/bin/sh
#

# Health Check for oc_erchef

# default return code is 0
rc=0

{{pkgPathFor "core/curl"}}/bin/curl -X GET -sS --head --fail --max-time 1 http://localhost:8000/_status

case $? in
    # Zero exit status means curl got back a 200 end everything is ok.
    0)
        rc=0 ;;
    # Anything else is critical.
    *)
        rc=2 ;;
esac

exit $rc
