#!/bin/bash

exec 2>&1

mkdir -p {{pkg.svc_var_path}}/logs

source "{{pkg.svc_config_path}}/database-migrations.sh"
# TODO: initial data setup (pivotal user, chef server containers, elasticsearch index, etc)
source "{{pkg.svc_config_path}}/elasticsearch-init.sh"
