#!/bin/bash
#
# Perform necessary private-chef setup steps after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
	exit 1
}

ln -sf /opt/opscode/bin/private-chef-ctl /usr/bin || error_exit "Cannot link private-chef-ctl in /usr/bin"
  
if [ -e /etc/opscode/chef-server-running.json ]; then
  echo -e "\033[1mYou have upgraded Private Chef!\033[0m"
  echo
  echo "The next step in the upgrade process is to run:"
  echo
  echo -e "\033[1;31mprivate-chef-ctl upgrade\033[0m"
else
  echo -e "\033[1mThank you for installing Private Chef!\033[0m"
fi

exit 0

