source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.0.4'
gem 'chef', '17.10.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.11'
gem 'jquery-rails'
gem 'jwt' # For Zendesk SSO
gem 'config', '~> 4.1' # Replacement of rails_config gem
gem 'rb-readline', '~> 0.5.2', require: false
gem 'sass-rails', '>= 4.0.3'
gem 'turbolinks', '~> 5'
gem 'unicorn-rails', '~> 2.2', '>= 2.2.1'
gem 'nokogiri', '1.14.3'
gem 'pg', '>= 0.18', '< 2.0' # active_record 4.2.8 pins this but doesn't manifest this in the gemspec for some reason
gem 'mixlib-authentication', '>= 2.1', '< 4'
gem 'responders', '~> 3.0', '>= 3.0.1'
gem 'doorkeeper', '~> 5.5'
gem "sprockets-rails", ">= 3.4.2"
gem 'mini_racer', '~> 0.6.2'
gem 'bigdecimal', '3.1.3'
gem 'veil', '~> 0.3.11'

gem 'omniauth-chef', '~> 0.4'
gem 'tzinfo-data'


#
# These gems require a javascript runtime.  We don't want to ship a
# javascript runtime so we put them in a separate group such that they
# don't get automatically required by rake.
#
group :node do
  gem 'coffee-rails', '~> 5.0'
  gem 'uglifier', '~> 4.2'
end

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'rails-controller-testing'
  gem 'pry-byebug'
  gem 'mailcatcher'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring' # App preloading
  gem 'spring-commands-rspec'
  gem 'thor', '~> 1.2'
end

group :doc do
  gem 'sdoc', require: false
end

group :test do
  gem 'capybara', '~> 3.38'
  gem 'factory_girl_rails', '~> 4.9.0'
  gem 'selenium-webdriver', '~> 4.7.1'
  gem 'timecop'
end
