require 'chef-utils/dist'

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
if ENV['CHEF_SECRETS_FD'].nil?
  ENV['CHEF_SECRETS_DATA'] ||= File.read(File.expand_path("../config/private-#{ChefUtils::Dist::Infra::SHORT}-secrets.json", __FILE__))
end

# Ensure bundler is set up and gems are available
require_relative 'config/boot'

# Load the Secrets class before the application to ensure it's available for database.yml parsing
require 'veil'
require_relative 'config/initializers/00_secrets'

require_relative 'config/application'

OcId::Application.load_tasks

task :default => :spec
