# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
if ENV['CHEF_SECRETS_FD'].nil?
  ENV['CHEF_SECRETS_DATA'] ||= File.read(File.expand_path("../config/private-chef-secrets.json", __FILE__))
end

require File.expand_path('../config/application', __FILE__)

OcId::Application.load_tasks

task :default => :spec
