# This file has been generated by cookbooks/dev/recipes/setup-knife.rb
#
node_name        'bobo'
client_name      'bobo'
client_key       'bobo.pem'
chef_server_url  'https://api.chef-server.dev/organizations/clownville'

