#!/bin/sh
exec 2>&1

export HOME={{pkg.svc_var_path}}
# export ERL_EPMD_ADDRESS=127.0.0.1

{{#if cfg.fips_enabled ~}}
export OPENSSL_FIPS=1
{{/if ~}}

# {{pkg.path}}/erts-7.3/bin/epmd -daemon

exec oc_bifrost foreground
