port=9463

[private_chef]
ip_mode="ipv4"
fips_enabled=false

[bifrost]

[lager]
lager_console_backend="info"

[sqerl]
db_host="localhost"
db_port=5432
db_user="bifrost"
db_pass="chefrocks"
db_name="bifrost"
db_pooler_timeout=2000
sql_db_timeout=5000

[webmachine]

[pooler.sqerl]
max_count=20
init_count=20
queue_max=200
