#!/bin/bash
#
# Perform necessary chef-server setup steps before package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
    echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
    exit 1
}

warn_about_search_reindex() {
    # If this is a fresh install, we don't need to worry about the
    # solr migration
    if [ ! -e /etc/opscode/chef-server-running.json ]; then
        return
    fi

    if [ -d /opt/opscode/sv/opscode-solr4 ]; then
        echo "############################ NOTICE ##################################"
        echo ""
        echo "It appears that this Chef Infra Server has Solr enabled."
        echo ""
        echo "By default, Chef Infra Server now uses Elasticsearch. To migrate to elasticsearch"
        echo "requires a full data reindex."
        echo ""
        echo "The reindex can take a long time if you have a large amount of data. Your Chef Infra Server"
        echo "will be down for the duration of the reindex."
        echo ""
        echo "We recommend taking a full backup before proceeding."
        echo ""
        echo "See https://docs.chef.io/server/upgrades/ for additional information on backups and upgrading."
        echo ""
        echo "############################ NOTICE ##################################"
    fi
}

save_pg_dir()
{
    # save the postgresql directory because it will be deleted by package upgrade
    sudo mkdir --verbose /tmp/opt-opscode-embedded-postgresql
    sudo cp --recursive --no-clobber --verbose /opt/opscode/embedded/postgresql/* /tmp/opt-opscode-embedded-postgresql
}

warn_about_search_reindex
save_pg_dir
exit 0
