source "https://rubygems.org"

# TODO pin some versions
# Let us configure redis instances for test setup
gem "redis"

# Probably redundant but it's why we're here.
gem "rspec"

# For testing of _route
gem "json"

