name             'oc-id'
maintainer       'Christian Nunciato'
maintainer_email 'cnunciato@getchef.com'
license          'All rights reserved'
description      'Installs/Configures oc-id, an OAuth 2 provider for Chef.'
version          '0.1.0'

supports 'ubuntu'

depends 'apt'
depends 'build-essential'
depends 'rsyslog'
depends 'runit'
depends 'users'
depends 'opscode-ruby'
depends 'opscode-github'
depends 'opscode-base'
depends 'opscode-lb'
depends 'opscode-xdarklaunch'
depends 'chef-vault'
depends 'deployment-notifications'
