source "http://rubygems.org"

gem "sequel", "~> 3.34.1"
gem "pg", "~> 0.16.0"
gem "veil", git: "https://github.com/chef/chef_secrets", branch: "main", ref: "51a81adeb85582b4acc905835c4f3d33e7216697"
# the below was there after rebasing onto mp's branch
gem "chef-utils", "~> 16.17"
