source "https://rubygems.org"

gemspec

gem "chef", git: "https://github.com/chef/chef", branch: "chef-18"
gem "toml" # for habitat-land

# Use latest commit from CHEF-23857-security-fix-test-ruby-3.1.7 branch for knife-ec-backup
gem "knife-ec-backup", git: "https://github.com/chef/knife-ec-backup", branch: "CHEF-23857-security-fix-test-ruby-3.1.7"
