source "https://rubygems.org"

gemspec

gem "rest-client", git: "https://github.com/chef/rest-client", branch: "jfm/ucrt_update1"

gem "chef", "~> 18.10.17"
gem "toml" # for habitat-land

gem "knife","~> 19.0.105"
gem "knife-ec-backup", "~> 3.0.8"
