
# Hitting an issue where appbundler is using development dependencies, so can't run bundle config set --local without development --deployment here
install:
	bundle install

travis: ci
	
ci:
	bundle exec rspec
